name: MSBuild

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: build/FusionDxHook.slnx
  SOLUTION_FILE_PATH64: build/FusionDxHook64.slnx
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@main
      
    - name: Configure build
      shell: cmd
      run: ./premake5.bat
      
    - name: Build x86
      shell: cmd
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=Win32 ${{env.SOLUTION_FILE_PATH}}

    - name: Build x64
      shell: cmd
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH64}}
      
    - name: Test
      shell: cmd
      run: |
        cd tests
        testDX.bat
